# Generated by Django 4.1.3 on 2022-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_registraion'),
        ('users', '0002_customuser_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='course',
        ),
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
